name: CI/CD + DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan repository for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bandit:
    needs: gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Security Scan
        run: |
          mkdir -p reports
          bandit -r . -ll -x checkers/baseline_eval -f txt -o reports/bandit-report.txt

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: reports/bandit-report.txt

  test:
    needs: bandit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          pytest

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t youssefrezk1/checkers:latest .

  trivy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t youssefrezk1/checkers:latest .

      - name: Create reports directory
        run: mkdir -p reports

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "youssefrezk1/checkers:latest"
          format: "table"
          output: "reports/trivy-report.txt"
          severity: "CRITICAL"
          ignore-unfixed: true
          exit-code: "1"

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: reports/trivy-report.txt

  docker-push:
    needs: trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t youssefrezk1/checkers:latest .

      - name: Push Docker image
        run: |
          docker push youssefrezk1/checkers:latest

  notify:
    needs: docker-push
    runs-on: ubuntu-latest

    steps:
      - name: Download Bandit Report
        uses: actions/download-artifact@v4
        with:
          name: bandit-report
          path: reports

      - name: Download Trivy Report
        uses: actions/download-artifact@v4
        with:
          name: trivy-report
          path: reports

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: "Checkers DevSecOps Pipeline Passed"

          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}

          attachments: |
            reports/bandit-report.txt
            reports/trivy-report.txt

          body: |
            DevSecOps Pipeline Completed Successfully

            Repository:
            ${{ github.repository }}

            Branch:
            ${{ github.ref_name }}

            Commit:
            ${{ github.sha }}

            Workflow:
            ${{ github.workflow }}

            Security Checks Completed:
            ✔ Gitleaks
            ✔ Bandit
            ✔ Pytest
            ✔ Docker Build
            ✔ Trivy
            ✔ Docker Push

            Bandit and Trivy reports are attached.

            Workflow Run:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
